pridexs/mainwebsite/urls.py
from django.conf.urls import url

from . import views

app_name="mainwebsite"
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^contact', views.contact, name='contact'),
]

pridexs/pridexs/urls.py
from django.conf.urls import include, url
from django.contrib import admin

from django.conf.urls.i18n import i18n_patterns
from django.utils.translation import ugettext_lazy as _

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^i18n/', include('django.conf.urls.i18n')),
]

urlpatterns += i18n_patterns(
    url(r'', include('mainwebsite.urls')),
)

handler404 = 'mainwebsite.views.handler404'
handler500 = 'mainwebsite.views.handler500'

pridexs/mainwebsite/models.py
from django.db import models

# Create your models here.

pridexs/mainwebsite/forms.py
from django import forms

class EmailForm(forms.Form):
    c_name = forms.CharField(label="Name", max_length=100)
    c_email = forms.EmailField()
    c_subject = forms.CharField(label="Subject", max_length=100)
    c_message = forms.CharField(widget=forms.Textarea)

pridexs/mainwebsite/views.py
import requests
from ipware.ip import get_real_ip

from django.shortcuts import render
from django.http import HttpResponseRedirect, HttpResponse
from django.core.urlresolvers import reverse
from django.views import generic
from django.core.mail import send_mail
from django.shortcuts import render_to_response
from django.template import RequestContext
from django.template import loader

from .forms import EmailForm

from django.conf import settings

def index(request):
    latest_question_list = []
    template = loader.get_template('mainwebsite/index.html')
    context = {
    }
    return HttpResponse(template.render(context, request))

def contact(request):

    context = {
        'email_sent': False,
        'error': False,
        'captcha_success': True,

    }

    if request.method == 'POST':
        if 'submit_message' in request.POST:
            form = EmailForm(request.POST)
            if form.is_valid():
                # Check if nocaptcha is successful
                data = request.POST
                captcha_rs = data.get('g-recaptcha-response')
                url = 'https://www.google.com/recaptcha/api/siteverify'
                params = {
                    'secret': settings.NOCAPTCHA_SECRET_KEY,
                    'response': captcha_rs,
                    'remoteip': get_real_ip(request)
                }
                verify_rs = requests.get(url, params=params, verify=True)
                verify_rs = verify_rs.json()

                senderName = form.cleaned_data['c_name']
                subject = form.cleaned_data['c_subject']
                message = form.cleaned_data['c_message']
                sender = form.cleaned_data['c_email']
                if verify_rs.get("success") == True:
                    recipients = ['contact@pridexs.com']
                    send_mail(subject, message, sender, recipients)
                    context['email_sent'] = True
                else:
                    context['senderName'] = senderName
                    context['subject'] = subject
                    context['message'] = message
                    context['sender'] = sender

                    context['captcha_success'] = False
            else:
                context['error'] = True

    template = loader.get_template('mainwebsite/contact.html')
    return HttpResponse(template.render(context, request))

def handler404(request):
    response = render_to_response('404.html', {},
                                  context_instance=RequestContext(request))
    response.status_code = 404
    return response


def handler500(request):
    response = render_to_response('500.html', {},
                                  context_instance=RequestContext(request))
    response.status_code = 500
    return response

pridexs/mainwebsite/templates/mainwebsite/contact.html
{% load i18n %}
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <title>{% trans "Pridexs - Contact" %}</title>

  <link href="{% static 'mainwebsite/css/bootstrap.min.css' %}" rel="stylesheet">
  <link href="{% static 'mainwebsite/css/ie10-viewport-bug-workaround.css' %}" rel="stylesheet">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.1/css/font-awesome.min.css">
  <link href="{% static 'mainwebsite/css/main.css' %}" rel="stylesheet">
  <link href='https://fonts.googleapis.com/css?family=Montserrat' rel='stylesheet' type='text/css'>
  <link href='https://fonts.googleapis.com/css?family=Questrial' rel='stylesheet' type='text/css'>

  <script>
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
    (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
    m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

    ga('create', 'UA-73124143-1', 'auto');
    ga('send', 'pageview');
  </script>

  <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
  <!--[if lt IE 9]>
  <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
  <![endif]-->

  <link rel="shortcut icon" href="{% static 'mainwebsite/images/favicon/favicon.ico' %}">
  <link rel="icon" sizes="16x16 32x32 64x64" href="{% static 'mainwebsite/images/favicon/favicon.ico' %}">
  <link rel="icon" type="image/png" sizes="196x196" href="{% static 'mainwebsite/images/favicon/favicon-192.png' %}">
  <link rel="icon" type="image/png" sizes="160x160" href="{% static 'mainwebsite/images/favicon/favicon-160.png' %}">
  <link rel="icon" type="image/png" sizes="96x96" href="{% static 'mainwebsite/images/favicon/favicon-96.png' %}">
  <link rel="icon" type="image/png" sizes="64x64" href="{% static 'mainwebsite/images/favicon/favicon-64.png' %}">
  <link rel="icon" type="image/png" sizes="32x32" href="{% static 'mainwebsite/images/favicon/favicon-32.png' %}">
  <link rel="icon" type="image/png" sizes="16x16" href="{% static 'mainwebsite/images/favicon/favicon-16.png' %}">
  <meta name="msapplication-TileColor" content="#FFFFFF">
  <meta name="msapplication-TileImage" content="images/favicon/favicon-144.png">
  <meta name="msapplication-config" content="images/favicon/browserconfig.xml">
  <script src='https://www.google.com/recaptcha/api.js'></script>
</head>

<body>

  <div class="container">
    <div class="header clearfix">
      <nav>
        <ul class="nav nav-pills pull-right">
          <li role="presentation"><a href="{% url 'mainwebsite:index' %}">{% trans "Home" %}</a></li>
          <li role="presentation" class="active"><a href="#">{% trans "Contact" %}</a></li>
        </ul>
      </nav>
      <h3 class="text-muted">Pridexs</h3>
    </div>

    <div class="language-selection">
      <ul class="list-inline pull-right">
        <li>{% trans "Language:" %}</li>
        <li>
            <form action="{% url 'set_language' %}" method="post">
                {% csrf_token %}
                <button class="btn btn-link" name="language" value="en">{% trans "English" %}</button>
            </form>
        </li>
        <li>
            <form action="{% url 'set_language' %}" method="post">
                {% csrf_token %}
                <button class="btn btn-link" name="language" value="pt-br">{% trans "Português" %}</button>
            </form>
        </li>
      </ul>
    </div>



    <div class="row information">
      {% if email_sent %}
      <div class="col-lg-12">
          <h3 class="success-msg">{% trans "Email sent!" %}</h3>
      </div>
      {% elif error %}
      <div class="col-lg-12">
          <h3 class="error-msg">{% trans "Error sending your Email :(" %}</h3>
      </div>
      {% elif not captcha_success %}
      <div class="col-lg-12">
          <h3 class="error-msg">{% trans "Are you a human?" %}</h3>
      </div>
      {% endif %}
      <div class="col-lg-12">
        <h1>{% trans "Contact me!" %}</h1>
      </div>
    </div>

    <form action="" method="POST">
      {% csrf_token %}
      <div class="row contact-form">
        <div class="col-lg-6 form-group">
          <label class="sr-only" for="c_name">{% trans "Name" %}</label>
          <input type="text" name="c_name" class="form-control" id="c_name" placeholder="{% trans "Name" %}" value="{{ senderName }}">
        </div>

        <div class="col-lg-6 form-group">
          <label class="sr-only" for="c_email">{% trans "Email Address" %}</label>
          <input type="email" name="c_email" class="form-control" id="c_email" placeholder="{% trans "Email" %}" value="{{ sender }}" required="true">
        </div>

        <div class="col-lg-12 form-group">
          <label class="sr-only" for="c_subject">{% trans "Subject" %}</label>
          <input type="text" name="c_subject" class="form-control" id="c_subject" placeholder="{% trans "Subject" %}" value="{{ subject }}">
        </div>

        <div class="col-lg-12 form-group">
          <textarea class="form-control" name="c_message" rows="10" id="c_message" placeholder="{% trans "Your secrets" %}" required="true">{{ message }}</textarea>
        </div>

        <div class="col-lg-12" style="height: 88px;">
          <div class="g-recaptcha" data-sitekey="6LcDTxcTAAAAAGUm-7qLNDgKgtLcVvhXy5R-7uuO"></div>
        </div>

        <div class="col-lg-12">
          <button type="submit" name="submit_message" class="btn btn-default">{% trans "Send" %}</button>
        </div>
      </div>
    </form>



    <footer class="footer">
      <p class="text-muted">&copy; 2016 Pridexs.</p>
    </footer>

  </div> <!-- /container -->


  <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
  <script src="{% static 'mainwebsite/js/ie10-viewport-bug-workaround.js' %}"></script>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
  <script src="{% static 'mainwebsite/js/bootstrap.min.js' %}"></script>
</body>
</html>

pridexs/mainwebsite/templates/mainwebsite/index.html
{% load i18n %}
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <title>{% trans "Pridexs - Home" %}</title>

  <link href="{% static 'mainwebsite/css/bootstrap.min.css' %}" rel="stylesheet">
  <link href="{% static 'mainwebsite/css/ie10-viewport-bug-workaround.css' %}" rel="stylesheet">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.1/css/font-awesome.min.css">
  <link href="{% static 'mainwebsite/css/main.css' %}" rel="stylesheet">
  <link href='https://fonts.googleapis.com/css?family=Montserrat' rel='stylesheet' type='text/css'>
  <link href='https://fonts.googleapis.com/css?family=Questrial' rel='stylesheet' type='text/css'>

  <script>
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
    (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
    m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

    ga('create', 'UA-73124143-1', 'auto');
    ga('send', 'pageview');
  </script>

  <link rel="shortcut icon" href="{% static 'mainwebsite/images/favicon/favicon.ico' %}">
  <link rel="icon" sizes="16x16 32x32 64x64" href="{% static 'mainwebsite/images/favicon/favicon.ico' %}">
  <link rel="icon" type="image/png" sizes="196x196" href="{% static 'mainwebsite/images/favicon/favicon-192.png' %}">
  <link rel="icon" type="image/png" sizes="160x160" href="{% static 'mainwebsite/images/favicon/favicon-160.png' %}">
  <link rel="icon" type="image/png" sizes="96x96" href="{% static 'mainwebsite/images/favicon/favicon-96.png' %}">
  <link rel="icon" type="image/png" sizes="64x64" href="{% static 'mainwebsite/images/favicon/favicon-64.png' %}">
  <link rel="icon" type="image/png" sizes="32x32" href="{% static 'mainwebsite/images/favicon/favicon-32.png' %}">
  <link rel="icon" type="image/png" sizes="16x16" href="{% static 'mainwebsite/images/favicon/favicon-16.png' %}">
  <meta name="msapplication-TileColor" content="#FFFFFF">
  <meta name="msapplication-TileImage" content="images/favicon/favicon-144.png">
  <meta name="msapplication-config" content="images/favicon/browserconfig.xml">
</head>

<body>

  <div class="container">
    <div class="header clearfix">
      <nav>
        <ul class="nav nav-pills pull-right">
          <li role="presentation" class="active"><a href="#">{% trans "Home" %}</a></li>
          <li role="presentation"><a href="{% url 'mainwebsite:contact' %}">{% trans "Contact" %}</a></li>
        </ul>
      </nav>
      <h3 class="text-muted">Pridexs</h3>
    </div>

    <div class="language-selection">
      <ul class="list-inline pull-right">
        <li>{% trans "Language:" %}</li>
        <li>
            <form action="{% url 'set_language' %}" method="post">
                {% csrf_token %}
                <button class="btn btn-link" name="language" value="en">{% trans "English" %}</button>
            </form>
        </li>
        <li>
            <form action="{% url 'set_language' %}" method="post">
                {% csrf_token %}
                <button class="btn btn-link" name="language" value="pt-br">{% trans "Português" %}</button>
            </form>
        </li>
      </ul>
    </div>

    <div class="jumbotron">
      <img src="{% static 'mainwebsite/images/pridexs_logo.png' %}" class="img-responsive" id="logo" alt="Pridexs Logo">
      <p class="lead">{% blocktrans with udesc_url='<a href="http://www.udesc.br/">UDESC</a>' %}Hi! I'm Alexandre 'Pridexs' Maros. Computer Science student at {{ udesc_url }} who likes to experiment with stuff.{% endblocktrans %}</p>

      <div class="row socials">
        <div class="col-lg-12">
          <a href="https://github.com/pridexs" class="fa fa-github-square"></a>
          <a href="https://www.linkedin.com/in/alexandre-maros-77b558110" class="fa fa-linkedin-square"></a>
          <a href="https://www.flickr.com/alehhh" class="fa fa-flickr"></a>
          <a href="https://www.instagram.com/pridexs/" class="fa fa-instagram"></a>
          <a href="http://steamcommunity.com/id/pridexs/" class="fa fa-steam-square"></a>
        </div>
      </div>
    </div>


    <div class="row information">
      <div class="col-lg-12">
        <h1>{% trans "About me" %}</h1>
        <p>{% trans "Currently studying Computer Science at UDESC - Santa Catarina, Brazil. I also studied abroad for one year at the Dublin Institute of Technology in Dublin, Ireland throug the Science Without Borders programme." %}</p>
        <p>{% blocktrans with github_url='<a href="github.com/pridexs">GitHub</a>' blog_url='<a href="http://blog.pridexs.com">Blog</a>' %}I love Computer Science and I am always trying to create something new, understand a new technology or mess around with existing ones. I don't often publish the stuff that I do, but I am trying to change that, so check my {{ github_url }} or my {{ blog_url }} for some ~maybe~ interesting little projects. {% endblocktrans %}</p>

        <h1>{% trans "Curent Projects" %}</h1>
        <p>{% trans "Here are a few projects that I am working on. They may not have information about them (I will add info as soon as possible!)" %}</p>
        <div class="row">
          <div class="col-lg-6">
            <h3><a href="http://blog.pridexs.com">{% trans "Blog" %}</a></h3>
            <p>{% trans "A place to write about whatever comes to my mind." %}</p>

            <h3>{% trans "Visual Identity" %}</h3>
            <p>{% trans "The visual identity guideline to pridexs.com and blog.pridexs.com" %}</p>
          </div>

          <div class="col-lg-6">
            <h3><a href="http://blog.pridexs.com/2016/04/extracting-data-from-mi-band/">{% trans "Extracting MiBand data" %}</a></h3>
            <p>{% trans "A way to extract Xiaomi's MiBand data from the app to use it in data visualization, etc." %}</p>

            <h3>{% trans "Life Goal Website" %}</h3>
            <p>{% trans "A way to keep track of your goals. Not yet available." %}</p>
          </div>
        </div>
      </div>
    </div>

    <footer class="footer">
      <p class="text-muted">&copy; 2016 Pridexs.</p>
    </footer>

  </div> <!-- /container -->

  <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
  <script src="{% static 'mainwebsite/js/ie10-viewport-bug-workaround.js' %}"></script>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
  <script src="{% static 'mainwebsite/js/bootstrap.min.js' %}"></script>
</body>
</html>